### ISSUE TITLE
no permite guardar resolucion

### ISSUE THREAD

**Issue by JHONF2078** [soenac/api-dian#2]
- el primer paso  crea el usuario y la empresa correctamente

![image](https://user-images.githubusercontent.com/8799088/63643140-f5ebb900-c68f-11e9-9d54-e56027b77685.png)

se almacena correctamente en la bd

![image](https://user-images.githubusercontent.com/8799088/63643157-2895b180-c690-11e9-8dd5-8cccbf1155a4.png)

- el segundo paso para crear una resolucion presenta error

![image](https://user-images.githubusercontent.com/8799088/63643163-43682600-c690-11e9-8d8c-345ef3a47639.png)

intente añadir el token de autorizacion como bearer token y desaparece el error pero no guarda la resolucion  (si utilizo en token almacenado en la bd tampoco me funciona)

![image](https://user-images.githubusercontent.com/8799088/63643181-83c7a400-c690-11e9-9c88-51728fb2824c.png)

agradezco de antemano   colaboración

**Comment by Stenfrank** [comment]
Validation request headers are incorrectly configured

**Comment by JHONF2078** [comment]
y  cual seria la configuracion corrrrecta, la verdad llevo un rato y no he pedido  

gracias

**Comment by Stenfrank** [comment]
https://learning.getpostman.com/docs/postman/sending_api_requests/requests/#header-presets

JSON
